send := send-sol.ts
cmint := create-token-mint.ts
mint := mint-tokens.ts
account := create-token-account.ts
meta := create-token-metadata.ts
# This Makefile is used to run TypeScript scripts using esrun
meta:
	npx esrun $(meta)
acc:
	npx esrun $(account)
send:
	npx esrun ${send}
mint:
	npx esrun ${mint}
cmint:
	npx esrun ${cmint}